### ISSUE TITLE
dylib install id question

### ISSUE THREAD

**Issue by dylanowen** [antoniusnaumann/cargo-swift#20]
I ran into this error on iOS but not the simulator:
```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: DYLD 1 Library missing
Library not loaded: /Users/*/librecipes2_lib.dylib
Referenced from: <CF59FA6C-EF6F-3660-B1DA-DA21ADF8B67A> /Volumes/VOLUME/*/recipes^2.app/recipes^2
Reason: tried: '/Users/*/librecipes2_lib.dylib' (no such file), '/private/preboot/Cryptexes/OS/Users/*/librecipes2_lib.dylib' (no such file), '/Users/*/librecipes2_lib.dylib' (no such file), '/usr/local/lib/librecipes2_lib.dylib' (no such file), '/usr/lib/librecipes2_lib.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
```

After extensive searching I realized the issue is that my rust library had its install id as `<my_path>/target/aarch64-apple-ios/debug/deps/librecipes2_lib.dylib`

With the help of these articles:
* <https://itwenty.me/2020/07/understanding-dyld-executable_path-loader_path-and-rpath/>
* <https://stackoverflow.com/questions/43054678/setting-xcode-linker-up-correctly-library-not-found-but-in-link-binary-with-l>

I realized changing it to `@rpath/librecipes2_lib.dylib` and rebuilding my XCode project fixed the issue since now the install id could be resolved using the runpath parameter.

My question: is this normal or is something wrong with my rust setup? If this is normal should the id remapping be part of this tool?

I remapped my id by running this on my library:
```
install_name_tool -id @rpath/librecipes2_lib.dylib librecipes2_lib.dylib
```

**Comment by antoniusnaumann** [comment]
This is indeed not expected behavior. I will look into it, thanks for pointing this out!

**Comment by antoniusnaumann** [comment]
Hi, I finally added this to ```cargo swift package``` command and verified that it built the example app correctly on an actual device (iPhone 12 running iOS 16.4). Would it be possible for you to check out the repository, install the current main branch and test it out? @dylanowen
