### ISSUE TITLE
Running cargo swift package

### ISSUE THREAD

**Issue by martinmose** [antoniusnaumann/cargo-swift#25]
Hello,

I apologize if this isn't ideal to open a issue for this inquiry. I'm new to Rust and attempting to work through the example provided. 

- `cargo swift init test`
- `cd test`
- `cargo swift package --name Test --platforms ios`

Then Im getting this error:

```
✔ Generating Swift bindings...                                                                                                                  
 x Building target iOS
    cargo build --target aarch64-apple-ios --target-dir ./target

Failed due to the following error:
    Updating crates.io index
   Compiling proc-macro2 v1.0.67
   Compiling unicode-ident v1.0.12
   Compiling serde v1.0.188
   Compiling thiserror v1.0.48
   Compiling serde_json v1.0.107
   Compiling camino v1.1.6
   Compiling semver v1.0.18
   Compiling anyhow v1.0.75
   Compiling version_check v0.9.4
   Compiling paste v1.0.14
   Compiling minimal-lexical v0.2.1
   Compiling unicase v2.7.0
   Compiling itoa v1.0.9
   Compiling memchr v2.6.3
   Compiling ryu v1.0.15
   Compiling nom v7.1.3
   Compiling mime v0.3.17
   Compiling once_cell v1.18.0
   Compiling bytes v1.5.0
   Compiling log v0.4.20
   Compiling siphasher v0.3.11
   Compiling askama_escape v0.10.3
   Compiling fs-err v2.9.0
   Compiling plain v0.2.3
   Compiling weedle2 v4.0.0
   Compiling heck v0.4.1
   Compiling glob v0.3.1
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-ios` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-ios`

error[E0463]: can't find crate for `compiler_builtins`

error[E0463]: can't find crate for `core`
  --> /Users/mha/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itoa-1.0.9/src/lib.rs:45:5
   |
45 | use core::mem::{self, MaybeUninit};
   |     ^^^^ can't find crate
   |
   = note: the `aarch64-apple-ios` target may not be installed
   = help: consider downloading the target with `rustup target add aarch64-apple-ios`

error[E0463]: can't find crate for `core`
  --> /Users/mha/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itoa-1.0.9/src/lib.rs:46:5
   |
46 | use core::{ptr, slice, str};
   |     ^^^^ can't find crate
   |
   = note: the `aarch64-apple-ios` target may not be installed
   = help: consider downloading the target with `rustup target add aarch64-apple-ios`

error: cannot find macro `debug_assert_eq` in this scope
  --> /Users/mha/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itoa-1.0.9/src/udiv128.rs:44:5
   |
44 |     debug_assert_eq!(quot, n / d as u128);
   |     ^^^^^^^^^^^^^^^

error: cannot find macro `debug_assert_eq` in this scope
  --> /Users/mha/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itoa-1.0.9/src/udiv128.rs:45:5
   |
45 |     debug_assert_eq!(rem as u128, n % d as u128);
   |     ^^^^^^^^^^^^^^^

error[E0405]: cannot find trait `Default` in this scope
  --> /Users/mha/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itoa-1.0.9/src/lib.rs:64:6
   |
64 | impl Default for Buffer {
   |      ^^^^^^^ not found in this scope

error[E0405]: cannot find trait `Copy` in this scope
  --> /Users/mha/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itoa-1.0.9/src/lib.rs:71:6
   |
71 | impl Copy for Buffer {}
   |      ^^^^ not found in this scope

error[E0405]: cannot find trait `Clone` in this scope
  --> /Users/mha/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itoa-1.0.9/src/lib.rs:73:6
   |
73 | impl Clone for Buffer {
   |      ^^^^^ not found in this scope

error[E0405]: cannot find trait `Copy` in this scope
   --> /Users/mha/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itoa-1.0.9/src/lib.rs:109:23
    |
109 |     pub trait Sealed: Copy {
    |                       ^^^^ not found in this scope

Some errors have detailed explanations: E0405, E0463.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `itoa` (lib) due to 10 previous errors
warning: build failed, waiting for other jobs to finish...
```

I can't figure out what Im missing.

`rustup target list | grep installed` gives me this output:
```
aarch64-apple-darwin (installed)
aarch64-apple-ios (installed)
aarch64-apple-ios-sim (installed)
x86_64-apple-darwin (installed)
x86_64-apple-ios (installed)
```

And my active toolchain looks fine as well:
`rustup show`
```
Default host: aarch64-apple-darwin
rustup home:  /Users/mha/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-apple-ios
aarch64-apple-ios-sim
x86_64-apple-darwin
x86_64-apple-ios

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.72.0 (5680fa18f 2023-08-23)
```

I have of course also tried `cargo clean`.

Would you be able to guide me or point me in the right direction?

**Comment by claudioitalian12** [comment]
I have fix with this: https://stackoverflow.com/questions/72504022/failed-to-follow-yew-tutorial-on-mac-m1-use-of-undeclared-type-vec       List of commands I have run:

rustup target remove wasm32-unknown-unknown
rustup self uninstall
brew uninstall rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup target add wasm32-unknown-unknown
cargo install --locked trunk
cargo clean
trunk clean
cargo install --locked wasm-bindgen-cli

# And finally
trunk serve

**Comment by martinmose** [comment]
@claudioitalian12, I appreciate your input!

You hit the nail on the head. The root cause of my issue was the Rust installation via Homebrew.

For the sake of future reference and anyone who might come across a similar issue, here are the commands I executed to rectify the situation:
1. `rustup self uninstall`
2. `brew uninstall rust`
3. `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
4. `cargo install cargo-swift`
5. `cargo swift package --name Test --platforms ios`

And got this output: 🥳

<img width="604" alt="image" src="https://github.com/antoniusnaumann/cargo-swift/assets/621570/77436a8d-d3fd-4e8e-be8c-c950903ad091">

On a related note, I found it peculiar that when using the Homebrew-installed Rust version, I didn't see any indication like Installing Toolchains. This added to my initial confusion.

Thanks once again for pointing me in the right direction!

**Comment by antoniusnaumann** [comment]
Good point, I should make it clear that rustup is required for installing toolchains, i.e. showing a message that toolchain installation was skipped if rustup is not available

**Comment by antoniusnaumann** [comment]
@martinmose Did you have rustup installed already when trying to run it with the homebrew version of Rust?

If yes, did you have the toolchains installed already? If yes, then it is expected that you don't get the "Installing toolchains" step. If no, I should look into this

**Comment by martinmose** [comment]
@antoniusnaumann,

I'm fairly new to Rust, so before diving in, I looked into installing Rust via Homebrew. (On a side note, I have a personal preference for using Homebrew whenever possible.)

It does make logical sense that the installation script wouldn't display "Installing toolchains" if it's not actually installing anything. However, I noticed distinct differences in the installation behavior when using Homebrew compared to the current Rust installation method I've adopted (`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`)
