### ISSUE TITLE
Upload to AppStore - ITMS-90426: Invalid Swift Support

### ISSUE THREAD

**Issue by martinmose** [antoniusnaumann/cargo-swift#35]
Hello,

I'm encountering an issue while trying to upload to the AppStore. 
Previously, I've successfully uploaded the app even with a shared Rust codebase. The main difference this time is that I'm using `cargo swift` instead of building the `.xcframework` myself 📦.

After the upload, I received this error:
```
ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. 
Rebuild your app using the current public (GM) version of Xcode and resubmit it.
```
I've explored various solutions online to no avail. I'm uncertain if this is related to `cargo swift` 🤔

Any insights or suggestions would be greatly appreciated! 🙏

**Comment by antoniusnaumann** [comment]
That's a tough one. I'll look into it, but no idea so far what is causing this.

Did you build the Swift package with the --release flag? Currently that's necessary.

**Comment by martinmose** [comment]
Thank you for getting back so swiftly, as always 💪.

Using `--lib-type static` solved the "issue"! 🥳
My apologies, I should've looked into that earlier. It's quite logical now that I think about it.

**Comment by antoniusnaumann** [comment]
I'm glad this solved the issue. (This was just a random guess 😅)

Thanks for reporting this, maybe I should deprecate the dylib option entirely (or find out if there is something missing that allows using dylib in App Store)

**Comment by martinmose** [comment]
I must say I'm partial to the dylib option. Given that I manage three separate repositories (iOS, Android, and Shared code), the ability to check in all necessary files is highly beneficial. Working with .a files poses challenges due to their size, especially when dealing with Git. If we could pinpoint what's preventing the use of dylib in the App Store, that would indeed be invaluable. 🙏

**Comment by antoniusnaumann** [comment]
Did you have a successful App Store build so far with dylibs?

**Comment by antoniusnaumann** [comment]
Let's move this discussion to #36
