### ISSUE TITLE
Publishing in App Store fails for dynamic libraries

### ISSUE THREAD

**Issue by antoniusnaumann** [antoniusnaumann/cargo-swift#36]
App Store Publishing fails for apps that use a package that includes a dylib as mentioned in #35

Either deprecate --lib-type dynamic or find out if there is a way to publish apps that contain packages build with this option.

**Comment by tapi** [comment]
I have some details here that might make it worth while reopening this. 

iOS does not support shipping dylibs on the appstore, only macos does. Docs are [here](https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle)
For iOS we need to convert it to a universal library using `lipo` and then bundle the library, the module map and the header as a framework. 

It may be worthwhile to do this for static libraries to produce static frameworks as well. It means simpler code in cargo-swift but it also allows for the inclusion of [xcprivacy manifests](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc) which Apple has started warning about and will be required in the future.

I was taking a crack at hand hacking the xcframework with frameworks but was getting issues in Xcode, the Swift wrapper could not see the uniffi header symbols, I was wondering if these [docs](https://mozilla.github.io/uniffi-rs/next/swift/module.html) might be related to the issue I was seeing.

If we can get dynamic frameworks working it would be awesome to include a step to generate [dsyms](https://users.rust-lang.org/t/missing-dsym-on-macos-when-building-with-cargo/97543/7) for them so stack traces can be decoded on platforms like Crashlytics, Bugsnage, etc
