### ISSUE TITLE
Unsafe flags in swiftSettings rejected by Xcode

### ISSUE THREAD

**Issue by trueb2** [antoniusnaumann/cargo-swift#40]
This was pretty easy to use! I hit one issue following the instructions and building with a new iOS app.

The package generated by `cargo swift package` fails to build when included in an iOS app due to the default Swift settings.
```swift
           swiftSettings: [
                .unsafeFlags(["-suppress-warnings"]),
            ]
```

Everything builds and runs if the flags are removed.
```swift
// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.
// Swift Package: asdf

import PackageDescription;

let package = Package(
    name: "asdf",
    platforms: [
        .iOS(.v13),
        .macOS(.v10_15)
    ],
    products: [
        .library(
            name: "asdf",
            targets: ["asdf"]
        )
    ],
    dependencies: [ ],
    targets: [
        .binaryTarget(name: "RustFramework", path: "./RustFramework.xcframework"),
        .target(
            name: "asdf",
            dependencies: [
                .target(name: "RustFramework")
            ],
            swiftSettings: [ ]
        )
    ]
)
```

**Comment by antoniusnaumann** [comment]
Thanks for pointing this out.

Does this happen when the generated package is added as a local dependency or as a remote dependency (e.g. via github)?

**Comment by antoniusnaumann** [comment]
The next version of cargo swift will remove this setting by default and add a "--suppress-warnings" flag to add this setting to the generated Package.swift if desired.

**Comment by RealVonmakeheat** [comment]
Ive commented out the `swiftSettings: [ /*  .unsafeFlags(["-suppress-warnings"]),*/ ]` and it still wont build for me ??

**Comment by martinmose** [comment]
I can see there is a difference if the generated Swift Package is include with:

```
let package = Package(
    ...
    dependencies: [
        .package(path: "Packages/Shared")
    ],
```

Or with the "Add local..." in the Package Dependencies.

I found this:
https://forums.swift.org/t/confused-by-unsafe-flags-being-disallowed-in-dependencies/27359/44

🤔

**Comment by antoniusnaumann** [comment]
> I can see there is a difference if the generated Swift Package is include with:
> 
> ```
> let package = Package(
>     ...
>     dependencies: [
>         .package(path: "Packages/Shared")
>     ],
> ```
> 
> Or with the "Add local..." in the Package Dependencies.
> 
> I found this: https://forums.swift.org/t/confused-by-unsafe-flags-being-disallowed-in-dependencies/27359/44
> 
> 🤔

Thanks for the comment. However, since cargo swift should also be able to produce packages intended for distribution (similar as maturin does for python), including the warning suppression as an option rather than as the default seems right here, since the flag might cause problems in some setups.
