### ISSUE TITLE
cannot be used as a dependency of this target because it uses unsafe build flags.

### ISSUE THREAD

**Issue by tomislaveric** [antoniusnaumann/cargo-swift#43]
Hi, i noticed that the build fails because it complains about unsafe build flags. This [change was introduced by the SPM](https://github.com/apple/swift-package-manager/pull/5632#event-7936949402) team. I am running Xcode 15.0.1. Here i get this error. However, the fix seems pretty simple. Pull Request is on its way

**Comment by antoniusnaumann** [comment]
This is already fixed on main. The new default behavior will be to not use the unsafe settings by default and include a flag to optionally toggle them.

If you know a way to silence warnings in the generated code without using unsafe settings, let me know.
