### ISSUE TITLE
How to pass different feature flags for each platform?

### ISSUE THREAD

**Issue by idzivinskyi** [antoniusnaumann/cargo-swift#48]
It currently builds for different platforms, for example:

cargo build --target x86_64-apple-darwin
cargo build --target aarch64-apple-darwin

How can I enable some features for `aarch64` specifically?

Thanks

**Comment by antoniusnaumann** [comment]
Unfortunately, this is not supported yet. 

Maybe there is a way to do this in your Cargo.toml instead of passing feature flags manually.

**Comment by idzivinskyi** [comment]
Thank you, here the workaround

```
[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
core = { path = "../core", features = ["metal"] }

[target.'cfg(not(all(target_os = "macos", target_arch = "aarch64")))'.dependencies]
core = { path = "../core" }
```
