### ISSUE TITLE
Error while generating swift bindings

### ISSUE THREAD

**Issue by coolbluewater** [antoniusnaumann/cargo-swift#52]
Hi! I ran into this error during the "Generating Swift bindings..." phase:
Could not generate UniFFI bindings for udl files due to the following error: No such file or directory

My library uses proc macros, not udl files. Is that the reason for this? Seems like a bug.

**Comment by antoniusnaumann** [comment]
This should work fine. I also can not reproduce this. Are you using version 0.6.0?

**Comment by coolbluewater** [comment]
I've modified my own scripts to create swift bindings due to the conditional compilation requirements so am not using cargo-swift.
